// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVwHrqFBzLiuoEsU5ybEiHdYnrEMK5SM0',
    appId: '1:852893931665:android:79d18cf167300af6260730',
    messagingSenderId: '852893931665',
    projectId: 'nemesis-finder',
    databaseURL: 'https://nemesis-finder-default-rtdb.firebaseio.com',
    storageBucket: 'nemesis-finder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxWriRvtMDLGycAYDjnDWfNHFnwxdC_J0',
    appId: '1:852893931665:ios:64c242a15e3ee41c260730',
    messagingSenderId: '852893931665',
    projectId: 'nemesis-finder',
    databaseURL: 'https://nemesis-finder-default-rtdb.firebaseio.com',
    storageBucket: 'nemesis-finder.appspot.com',
    androidClientId: '852893931665-85nsfmkjmngmi7qksmoofphaov92j99h.apps.googleusercontent.com',
    iosClientId: '852893931665-uflpvnt4cco7f22rggebnpijrffh2iao.apps.googleusercontent.com',
    iosBundleId: 'com.example.nemesis',
  );
}
